version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  redis:
    image: redis
    ports:
      - '6379:6379'
